### ISSUE TITLE
ERROR! 'pylxca_module' is not a valid attribute for a Play

### ISSUE THREAD

**Issue by benboreham** [lenovo/ansible-role-lxca-inventory#13]
Using the example given in the readme:

inventory.yml (Updated to add code block)
```
- name: get nodes data from LXCA
    pylxca_module:
      login_user: "{{ lxca_user }}"
      login_password: "{{ lxca_password }}"
      auth_url: "{{ lxca_url }}"
      command_options: nodes
    register: rslt
    tags:
       nodes
```

I run: ansible-playbook -e "lxca_user=REDACTED lxca_password=REDACTED lxca_url=REDACTED" inventory.yml -vvvv

But I get this error:
`ERROR! 'pylxca_module' is not a valid attribute for a Play

The error appears to be in '/home/ubuntu/inventory.yml': line 3, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

- name: get nodes data from LXCA
  ^ here`
  
  
pylxca is installed as per the readme:
  
pip install pylxca
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pylxca in /usr/local/lib/python3.10/dist-packages (3.2.0)
Requirement already satisfied: requests-toolbelt>=0.8.0 in /usr/lib/python3/dist-packages (from pylxca) (0.9.1)
Requirement already satisfied: unittest2 in /usr/lib/python3/dist-packages (from pylxca) (1.1.0)
Requirement already satisfied: requests>=2.7.0 in /usr/lib/python3/dist-packages (from pylxca) (2.25.1)
  

As well as ansible:
ansible --version
ansible 2.10.8

**Comment by prabhosa** [comment]
@benboreham Looking into the issue. Will keep you posted

**Comment by benboreham** [comment]
Thanks prabhosa,

I've also tried the following:
```
---

- name: get nodes data from LXCA
  tasks:
    - name: get nodes
      pylxca_module:
        login_user: "{{ lxca_user }}"
        login_password: "{{ lxca_password }}"
        auth_url: "{{ lxca_url }}"
        command_options: nodes
      register: rslt
      tags:
        - nodes
```

Which gives a different error:
```
ERROR! couldn't resolve module/action 'pylxca_module'. This often indicates a misspelling, missing collection, or incorrect module path.

The error appears to be in '/home/ubuntu/inventory.yml': line 5, column 7, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

  tasks:
    - name: get nodes
      ^ here
      ```

**Comment by saysudheer** [comment]
@benboreham update inventory.yml to this playbook script which should also have hosts and connection attributes.

---
- name: Get nodes data from LXCA
  hosts: localhost
  connection: local
  tasks:
    - name: Use pylxca_module
      pylxca_module:
        login_user: "{{ lxca_user }}"
        login_password: "{{ lxca_password }}"
        auth_url: "{{ lxca_url }}"
        command_options: nodes
      register: rslt
      tags:
        - nodes
-------------------------------------------------------------------------------------------------------------        
playbook command to run :

Failed case:
-------------------------------------------------------------------------------------------------------------
ansible-playbook -e "lxca_user=USER lxca_password=LXCA lxca_url=ipaddress" inventory.yml  -vvv 
-------------------------------------------------------------------------------------------------------------

this above playbook command will give a failed response as below. 

localhost: ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
-------------------------------------------------------------------------------------------------------------
Success case:

PLAY [Get nodes data from LXCA] ********************************************************************************************************************

TASK [Gathering Facts] *****************************************************************************************************************************
ok: [localhost]

TASK [Use pylxca_module] ***************************************************************************************************************************
ok: [localhost]

PLAY RECAP *****************************************************************************************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0

**Comment by benboreham** [comment]
Thanks for your recommendation saysudheer.

I added the recommended lines and inventory.yml now looks like this

```
#Usage: ansible-playbook -e "lxca_user=<username> lxca_password=<password> lxca_url=<xClairyIP>" inventory.yml -vvv

- name: get nodes data from LXCA
  hosts: localhost
  connection: local
  tasks:
    - name: get nodes
      pylxca_module:
        login_user: "{{ lxca_user }}"
        login_password: "{{ lxca_password }}"
        auth_url: "{{ lxca_url }}"
        command_options: nodes
      register: rslt
      tags:
        - nodes

```


But I still get the same error:

```
ansible-playbook 2.10.8
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/ubuntu/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  executable location = /usr/bin/ansible-playbook
  python version = 3.10.6 (main, Nov 14 2022, 16:10:14) [GCC 11.3.0]
Parsed /etc/ansible/hosts inventory source with ini plugin
ERROR! couldn't resolve module/action 'pylxca_module'. This often indicates a misspelling, missing collection, or incorrect module path.

The error appears to be in '/home/ubuntu/ansible-lenovo/inventory.yml': line 8, column 7, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

  tasks:
    - name: get nodes
      ^ here
```


I suspect that there's something I need to configure in ansible.cfg so that it can see pylxca_module is installed?

I'm able to run `sudo lxca_shell`  though 
```
/usr/lib/python3/dist-packages/pkg_resources/__init__.py:116: PkgResourcesDeprecationWarning: 0.1.43ubuntu1 is an invalid version and will not be supported in a future release
  warnings.warn(
/usr/lib/python3/dist-packages/pkg_resources/__init__.py:116: PkgResourcesDeprecationWarning: 1.1build1 is an invalid version and will not be supported in a future release
  warnings.warn(

--------------------------------------------------
Welcome to LXCA Command Shell v2.7.0
Type "help" at any time for a list of commands.
Use "lxca_shell --api" to enable Interactive Python LXCA Shell
--------------------------------------------------

PyLXCA >>
```

Thanks for your assistance.
